from pathlib import Path

from src.file_ownership_classifier import build_file_ownership_facts


def test_build_file_ownership_facts(tmp_path: Path) -> None:
    generated_file = tmp_path / "a.generated.py"
    locked_file = tmp_path / "b.py"
    manual_file = tmp_path / "c.py"
    unknown_file = tmp_path / "d.bin"

    generated_file.write_text("# @generated\n", encoding="utf-8")
    locked_file.write_text("# @locked\n", encoding="utf-8")
    manual_file.write_text("def foo():\n    pass\n", encoding="utf-8")
    unknown_file.write_bytes(b"\xff")

    ownership_facts = build_file_ownership_facts(tmp_path)

    assert ownership_facts == [
        {"file_path": "a.generated.py", "ownership": "generated"},
        {"file_path": "b.py", "ownership": "locked"},
        {"file_path": "c.py", "ownership": "manual"},
        {"file_path": "d.bin", "ownership": "unknown"},
    ]


def test_governed_classification(tmp_path: Path) -> None:
    (tmp_path / "a.py").write_text("# @governed\n", encoding="utf-8")
    (tmp_path / "b.py").write_text("# ownership: governed\n", encoding="utf-8")

    facts = {f["file_path"]: f["ownership"] for f in build_file_ownership_facts(tmp_path)}
    assert facts["a.py"] == "governed"
    assert facts["b.py"] == "governed"


def test_critical_classification(tmp_path: Path) -> None:
    (tmp_path / "a.py").write_text("# @critical\n", encoding="utf-8")
    (tmp_path / "b.py").write_text("# ownership: critical\n", encoding="utf-8")

    facts = {f["file_path"]: f["ownership"] for f in build_file_ownership_facts(tmp_path)}
    assert facts["a.py"] == "critical"
    assert facts["b.py"] == "critical"


def test_policy_sensitive_classification(tmp_path: Path) -> None:
    (tmp_path / "a.py").write_text("# @policy-sensitive\n", encoding="utf-8")
    (tmp_path / "b.py").write_text("# @policy_sensitive\n", encoding="utf-8")
    (tmp_path / "c.py").write_text("# ownership: policy-sensitive\n", encoding="utf-8")
    (tmp_path / "d.py").write_text("# ownership: policy_sensitive\n", encoding="utf-8")

    facts = {f["file_path"]: f["ownership"] for f in build_file_ownership_facts(tmp_path)}
    assert facts["a.py"] == "policy_sensitive"
    assert facts["b.py"] == "policy_sensitive"
    assert facts["c.py"] == "policy_sensitive"
    assert facts["d.py"] == "policy_sensitive"


def test_content_based_generated_classification(tmp_path: Path) -> None:
    markers = [
        ("a.py", "# auto-generated\n"),
        ("b.py", "# autogenerated\n"),
        ("c.py", "# generated by foo\n"),
        ("d.py", "# this file was generated\n"),
        ("e.py", "# do not edit\n"),
    ]
    for name, content in markers:
        (tmp_path / name).write_text(content, encoding="utf-8")

    facts = {f["file_path"]: f["ownership"] for f in build_file_ownership_facts(tmp_path)}
    for name, _ in markers:
        assert facts[name] == "generated", f"{name} should be generated"


def test_ownership_markers_take_priority_over_generated_content(tmp_path: Path) -> None:
    # A file with both an ownership marker and a generated marker yields the ownership category.
    (tmp_path / "a.py").write_text("# @locked\n# auto-generated\n", encoding="utf-8")

    facts = {f["file_path"]: f["ownership"] for f in build_file_ownership_facts(tmp_path)}
    assert facts["a.py"] == "locked"


def test_credential_adjacent_env_files(tmp_path: Path) -> None:
    (tmp_path / ".env").write_text("DATABASE_URL=postgres://localhost/db\n", encoding="utf-8")
    (tmp_path / ".env.local").write_text("SECRET_KEY=dev\n", encoding="utf-8")
    (tmp_path / ".env.production").write_text("SECRET_KEY=prod\n", encoding="utf-8")

    facts = {f["file_path"]: f["ownership"] for f in build_file_ownership_facts(tmp_path)}
    assert facts[".env"] == "policy_sensitive"
    assert facts[".env.local"] == "policy_sensitive"
    assert facts[".env.production"] == "policy_sensitive"


def test_credential_adjacent_key_and_cert_files(tmp_path: Path) -> None:
    for name in ("server.pem", "server.key", "server.crt", "server.cer", "server.der", "server.csr"):
        (tmp_path / name).write_text("-----BEGIN CERTIFICATE-----\n", encoding="utf-8")
    # Use bytes that are invalid UTF-8 to exercise the UnicodeDecodeError path.
    (tmp_path / "keystore.p12").write_bytes(b"\xff\xfe\x00\x01")
    (tmp_path / "keystore.pfx").write_bytes(b"\xff\xfe\x00\x01")

    facts = {f["file_path"]: f["ownership"] for f in build_file_ownership_facts(tmp_path)}
    for name in ("server.pem", "server.key", "server.crt", "server.cer", "server.der", "server.csr"):
        assert facts[name] == "policy_sensitive", f"{name} should be policy_sensitive"
    # Binary credential files that cannot be decoded are still policy_sensitive — the
    # filename is sufficient structural evidence.
    assert facts["keystore.p12"] == "policy_sensitive"
    assert facts["keystore.pfx"] == "policy_sensitive"


def test_ownership_markers_take_priority_over_credential_filename(tmp_path: Path) -> None:
    # An explicit ownership annotation overrides the credential filename heuristic.
    (tmp_path / ".env").write_text("# @locked\nSECRET_KEY=x\n", encoding="utf-8")

    facts = {f["file_path"]: f["ownership"] for f in build_file_ownership_facts(tmp_path)}
    assert facts[".env"] == "locked"


def test_filename_generated_takes_priority_over_content_markers(tmp_path: Path) -> None:
    # A .generated. filename is classified without reading content.
    (tmp_path / "a.generated.py").write_text("# @locked\n", encoding="utf-8")

    facts = {f["file_path"]: f["ownership"] for f in build_file_ownership_facts(tmp_path)}
    assert facts["a.generated.py"] == "generated"
