from __future__ import annotations

from pathlib import Path

from src.repo_scanner import scan_repository


OWNERSHIP_MARKERS = (
    ("locked", ("@locked", "ownership: locked")),
    ("governed", ("@governed", "ownership: governed")),
    ("critical", ("@critical", "ownership: critical")),
    (
        "policy_sensitive",
        (
            "@policy-sensitive",
            "@policy_sensitive",
            "ownership: policy-sensitive",
            "ownership: policy_sensitive",
        ),
    ),
)

CREDENTIAL_FILE_SUFFIXES = frozenset({
    ".pem", ".key", ".p12", ".pfx", ".crt", ".cer", ".der", ".csr",
})


def _is_credential_adjacent_filename(file_path: Path) -> bool:
    name = file_path.name.lower()
    if name == ".env" or name.startswith(".env."):
        return True
    return file_path.suffix.lower() in CREDENTIAL_FILE_SUFFIXES


GENERATED_FILE_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "generated by",
    "this file was generated",
    "do not edit",
)


def _classify_file_ownership(file_path: Path, root: Path) -> str:
    relative_file_path = str(file_path.relative_to(root)).lower()
    if ".generated." in relative_file_path:
        return "generated"

    try:
        content = file_path.read_text(encoding="utf-8").lower()
    except UnicodeDecodeError:
        if _is_credential_adjacent_filename(file_path):
            return "policy_sensitive"
        return "unknown"

    for ownership, markers in OWNERSHIP_MARKERS:
        if any(marker in content for marker in markers):
            return ownership

    if _is_credential_adjacent_filename(file_path):
        return "policy_sensitive"

    if any(marker in content for marker in GENERATED_FILE_MARKERS):
        return "generated"

    return "manual"


def build_file_ownership_facts(root: Path) -> list[dict[str, str]]:
    ownership_facts: list[dict[str, str]] = []

    for file_path in scan_repository(root):
        ownership_facts.append(
            {
                "file_path": str(file_path.relative_to(root)),
                "ownership": _classify_file_ownership(file_path, root),
            }
        )

    return sorted(ownership_facts, key=lambda ownership_fact: ownership_fact["file_path"])
